remote_theme: pages-themes/slate@v0.2.0
title: Central Texas Disc Golf Community
description: The hub for Central Texas disc golfers to meet, chat, and grow. Accesible on Discord.
kramdown:
  input: Kramdown
